/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesResearchIntelligenceRouteImport } from './routes/services.research-intelligence'
import { Route as ServicesDataAnalysisRouteImport } from './routes/services.data-analysis'
import { Route as ServicesCreativeVisualRouteImport } from './routes/services.creative-visual'
import { Route as ServicesContentCopywritingRouteImport } from './routes/services.content-copywriting'
import { Route as ServicesChatbotsAutomationRouteImport } from './routes/services.chatbots-automation'
import { Route as ServicesBusinessOperationsRouteImport } from './routes/services.business-operations'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesResearchIntelligenceRoute =
  ServicesResearchIntelligenceRouteImport.update({
    id: '/services/research-intelligence',
    path: '/services/research-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesDataAnalysisRoute = ServicesDataAnalysisRouteImport.update({
  id: '/services/data-analysis',
  path: '/services/data-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCreativeVisualRoute = ServicesCreativeVisualRouteImport.update({
  id: '/services/creative-visual',
  path: '/services/creative-visual',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesContentCopywritingRoute =
  ServicesContentCopywritingRouteImport.update({
    id: '/services/content-copywriting',
    path: '/services/content-copywriting',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesChatbotsAutomationRoute =
  ServicesChatbotsAutomationRouteImport.update({
    id: '/services/chatbots-automation',
    path: '/services/chatbots-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBusinessOperationsRoute =
  ServicesBusinessOperationsRouteImport.update({
    id: '/services/business-operations',
    path: '/services/business-operations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/services/business-operations': typeof ServicesBusinessOperationsRoute
  '/services/chatbots-automation': typeof ServicesChatbotsAutomationRoute
  '/services/content-copywriting': typeof ServicesContentCopywritingRoute
  '/services/creative-visual': typeof ServicesCreativeVisualRoute
  '/services/data-analysis': typeof ServicesDataAnalysisRoute
  '/services/research-intelligence': typeof ServicesResearchIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/services/business-operations': typeof ServicesBusinessOperationsRoute
  '/services/chatbots-automation': typeof ServicesChatbotsAutomationRoute
  '/services/content-copywriting': typeof ServicesContentCopywritingRoute
  '/services/creative-visual': typeof ServicesCreativeVisualRoute
  '/services/data-analysis': typeof ServicesDataAnalysisRoute
  '/services/research-intelligence': typeof ServicesResearchIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/services/business-operations': typeof ServicesBusinessOperationsRoute
  '/services/chatbots-automation': typeof ServicesChatbotsAutomationRoute
  '/services/content-copywriting': typeof ServicesContentCopywritingRoute
  '/services/creative-visual': typeof ServicesCreativeVisualRoute
  '/services/data-analysis': typeof ServicesDataAnalysisRoute
  '/services/research-intelligence': typeof ServicesResearchIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/services/business-operations'
    | '/services/chatbots-automation'
    | '/services/content-copywriting'
    | '/services/creative-visual'
    | '/services/data-analysis'
    | '/services/research-intelligence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/services/business-operations'
    | '/services/chatbots-automation'
    | '/services/content-copywriting'
    | '/services/creative-visual'
    | '/services/data-analysis'
    | '/services/research-intelligence'
  id:
    | '__root__'
    | '/'
    | '/pricing'
    | '/services/business-operations'
    | '/services/chatbots-automation'
    | '/services/content-copywriting'
    | '/services/creative-visual'
    | '/services/data-analysis'
    | '/services/research-intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricingRoute: typeof PricingRoute
  ServicesBusinessOperationsRoute: typeof ServicesBusinessOperationsRoute
  ServicesChatbotsAutomationRoute: typeof ServicesChatbotsAutomationRoute
  ServicesContentCopywritingRoute: typeof ServicesContentCopywritingRoute
  ServicesCreativeVisualRoute: typeof ServicesCreativeVisualRoute
  ServicesDataAnalysisRoute: typeof ServicesDataAnalysisRoute
  ServicesResearchIntelligenceRoute: typeof ServicesResearchIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/research-intelligence': {
      id: '/services/research-intelligence'
      path: '/services/research-intelligence'
      fullPath: '/services/research-intelligence'
      preLoaderRoute: typeof ServicesResearchIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/data-analysis': {
      id: '/services/data-analysis'
      path: '/services/data-analysis'
      fullPath: '/services/data-analysis'
      preLoaderRoute: typeof ServicesDataAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/creative-visual': {
      id: '/services/creative-visual'
      path: '/services/creative-visual'
      fullPath: '/services/creative-visual'
      preLoaderRoute: typeof ServicesCreativeVisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/content-copywriting': {
      id: '/services/content-copywriting'
      path: '/services/content-copywriting'
      fullPath: '/services/content-copywriting'
      preLoaderRoute: typeof ServicesContentCopywritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/chatbots-automation': {
      id: '/services/chatbots-automation'
      path: '/services/chatbots-automation'
      fullPath: '/services/chatbots-automation'
      preLoaderRoute: typeof ServicesChatbotsAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/business-operations': {
      id: '/services/business-operations'
      path: '/services/business-operations'
      fullPath: '/services/business-operations'
      preLoaderRoute: typeof ServicesBusinessOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingRoute: PricingRoute,
  ServicesBusinessOperationsRoute: ServicesBusinessOperationsRoute,
  ServicesChatbotsAutomationRoute: ServicesChatbotsAutomationRoute,
  ServicesContentCopywritingRoute: ServicesContentCopywritingRoute,
  ServicesCreativeVisualRoute: ServicesCreativeVisualRoute,
  ServicesDataAnalysisRoute: ServicesDataAnalysisRoute,
  ServicesResearchIntelligenceRoute: ServicesResearchIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
